spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./db;AUTO_SERVER=true"
    username: "sa"
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor: trace
